import { IPrimativeQuestion } from '../../../Interfaces/IQuestion';

const QuestionsMedium: IPrimativeQuestion[] = [
  {
    id: 1,
    name: 'questionA',
    question: 'Em que ano a escola de Hogwarts foi fundada?',
    answerA: '101 D.C.',
    answerB: '993 D.C',
    answerC: '12 A.C.',
    answerD: '817 D.C.',
  },
  {
    id: 2,
    name: 'questionB',
    question: 'Qual alternativa abaixo contém apenas os nomes do fundadores reais de Hogwarts:',
    answerA: 'Gorlic, Salssazar, Helga, Ravina',
    answerB: 'Godric, Beltessazar, Helena, Rowena',
    answerC: 'Godric, Salazar, Helga, Rowena',
    answerD: 'Gadric, Salsazar, Helena, Rowwina',
  },
  {
    id: 3,
    name: 'questionC',
    question: 'Quais eram as horcruxes, na ordem exata em que aparecem no filme?',
    answerA: 'Diário de Tom Riddle, Anel de Servolo, Medalhão de Slytherin, Taça de Hufflepuff, Diadema de Ravenclaw, Nagini, Harry Potter',
    answerB: 'Diário de Tom Riddle, Taça de Hufflepuff, Anel de Servolo, Diadema de Ravenclaw, Medalhão de Slytherin, Nagini, Harry Potter',
    answerC: 'Anel de Servolo, Diário de Tom Riddle, Medalhão de Slytherin, Diadema de Ravenclaw, Taça de Hufflepuff, Nagini, Harry Potter',
    answerD: 'Diadema de Ravenclaw, Diário de Tom Riddle, Medalhão de Slytherin, Anel de Servolo, Taça de Hufflepuff, Nagini, Harry Potter',
  },
  {
    id: 4,
    name: 'questionD',
    question: 'Qual o nome real de Voldemort?',
    answerA: 'Thomas Maroto Rivle',
    answerB: 'Thimothy Marvollus Readle',
    answerC: 'Tom Marvellus Riddle',
    answerD: 'Tom Marvolo Riddle',
  },
  {
    id: 5,
    name: 'questionE',
    question: 'Quantas pessoas haviam na Ordem da Fênix original e na Nova Ordem, respectivamente?',
    answerA: '24, 21',
    answerB: '21, 24',
    answerC: '24, 17',
    answerD: '21, 20',
  },
  {
    id: 6,
    name: 'questionF',
    question: 'Qual é a estrutura da varinha de Bellatrix?',
    answerA: 'Oliveira, 31,85cm, flexível, corda de coração de dragão',
    answerB: 'Nogueira Negra, 33,70cm, semi-flexível, cauda de dragão',
    answerC: 'Carvalho, 28,90cm, inflexível, pelo de bode das montanhas',
    answerD: 'Nogueira, 32,38cm, inflexível, corda de coração de dragão',
  },
  {
    id: 7,
    name: 'questionG',
    question: 'Hagrid leva o bebê Potter em uma moto, no primeiro filme. De quem é a moto?',
    answerA: 'Dele mesmo',
    answerB: 'Pedro Petigrew',
    answerC: 'Sirius Black',
    answerD: 'Aberforth Dumbledore',
  },
  {
    id: 8,
    name: 'questionH',
    question: 'Quem foi o 1º a encontrar a Sala Precisa?',
    answerA: 'Harry Potter',
    answerB: 'Voldemort',
    answerC: 'Filtch',
    answerD: 'Dumbledore',
  },
  {
    id: 9,
    name: 'questionI',
    question: 'Quem recuperou o Medalhão de Slytherin antes de Harry Potter e sua trupe, guardando-o na casa sede da Ordem da Fênix?',
    answerA: 'Sirius Black',
    answerB: 'Rowena Ravenclaw',
    answerC: 'Regulus Black',
    answerD: 'Aberforth Dumbledore',
  },
  {
    id: 10,
    name: 'questionJ',
    question: 'Qual o nome do feitiço que a professora Minerva usa para liberar os soldados do Castelo de Hogwarts na batalha final?',
    answerA: 'Piertoteum Locomotora',
    answerB: 'Piertototum Lacomora',
    answerC: 'Piertotum Lotomotor',
    answerD: 'Piertotum Locomotor',
  },
];

export default QuestionsMedium;
