/* eslint-disable max-len */
import { IPrimativeQuestion } from '../../../Interfaces/IQuestion';

const QuestionsMedium: IPrimativeQuestion[] = [
  {
    id: 1,
    name: 'questionA',
    question: 'Qual é o patrono de Hagrid?',
    answerA: 'Um dragão chinês',
    answerB: 'Um tigre de bengala',
    answerC: 'Uma aranha gigante',
    answerD: 'Nenhum',
  },
  {
    id: 2,
    name: 'questionB',
    question: 'Luna casou-se com o neto de Newt Scamandader. Quantos filhos eles tiveram e quais eram seus nomes?',
    answerA: 'Não tiveram filhos',
    answerB: '2 filhos: Layon e Elisander',
    answerC: '1 filha: Lavena Scamander',
    answerD: '2 filhos: Lorcan e Lysander',
  },
  {
    id: 3,
    name: 'questionC',
    question: 'O que eram os: Sagrados Vinte e Oito?',
    answerA: 'Um grupo de aurores, formados nas diversas escolas de magia do séc. XIX',
    answerB: 'Um conjunto de livros antigos que possuia magias secretas e únicas, entre combinações de feitiços e conjurações',
    answerC: 'Uma lista, publicada em meados dos anos 30, que descrevia todas as famílias de sangue puro',
    answerD: 'Um evento astronômico que ocorreu em 202 D.C., alinhando 28 astros numa conjunção única e rara',
  },
  {
    id: 4,
    name: 'questionD',
    question: 'Qual das opções abaixo descreve com exatidão quem foi Quim Shacklebolt:',
    answerA: 'Um comensal da morte, que trabalhava infiltrado no Ministério da Magia mas que precisou se esconder, após a queda de Voldemort em 1991',
    answerB: 'Um auror, que possui uma loja de artigos de Magia em Hogsmeade e detentor de livros raríssimos, cobiçados por bruxos em todo o mundo',
    answerC: 'Um auror, que auxiliou na proteção de Harry Potter, trabalhando infiltrado no Ministério e se tornou após a batalha final, o novo Ministro da magia',
    answerD: 'Um professor de Hogwarts que ensinava Poções no período de 1916, quando Tom Riddle estava em seu 3º ano letivo. Possuía um grande interesse em dragões e criaturas mágicas',
  },
  {
    id: 5,
    name: 'questionE',
    question: 'Cuthbert Binns era professor de História da Magia na Escola de Magia e Bruxaria de Hogwarts. Ele adormeceu um dia na sala dos professores e morreu em sono. Hoje, é um fantasma de Hogwarts que vive falando sobre certos assuntos com os alunos. Quais?',
    answerA: 'Sobre a história dos bruxos antigos e magos famosos que existiram, sobre seus feitos e também, sobre suas intimidades e segredos',
    answerB: 'Sobre as várias rebeliões dos duendes e guerras dos gigantes',
    answerC: 'Sobre dragões, elfos, fadas e trasgos, sendo estes (trasgos), sua maior paixão e curiosidade',
    answerD: 'Sobre os maiores acontecimentos do mundo bruxo, desde A.C. até a atualidade',
  },
  {
    id: 6,
    name: 'questionF',
    question: 'Quando foi que a escritora J.K. Rowling escreveu o último capítulo do último livro da saga Harry Potter?',
    answerA: 'Em meados de 1990, 12 anos antes do lançamento do 1º livro',
    answerB: 'Em meados de 1990, 7 anos antes do lançamento do 1º livro',
    answerC: 'Em meados de 1988, 14 anos antes do lançamento do 1º livro',
    answerD: 'Em meados de 1991, 5 anos antes do lançamento do 1º livro',
  },
  {
    id: 7,
    name: 'questionG',
    question: 'Qual era o nome da atriz que interpretou a Murta que Geme e quantos anos ela tinha na época do lançamento do filme?',
    answerA: 'Shirley Henderson, 40 anos',
    answerB: 'Shautney Caurteman, 22 anos',
    answerC: 'Sharlote Heitterson, 30 anos',
    answerD: 'Shanden Hamley, 21 anos',
  },
  {
    id: 8,
    name: 'questionH',
    question: 'Quais eram os patronos de Rony Weasley, Hermione Granger, Aberforth Dumbledore e Luna Lovegood?',
    answerA: 'Um cachorro, uma doninha, um cavalo e uma borboleta',
    answerB: 'Um sapo, uma raposa, um bode e uma serpente',
    answerC: 'Um cachorro, uma lontra, uma cabra e uma lebre',
    answerD: 'Um cachorro, uma doninha, uma lontra e um cisne',
  },
  {
    id: 9,
    name: 'questionI',
    question: 'J.K. Rowling considerou matar um(a) dos(as) personagens durante a série. Mas reconsiderou e o(a) manteve vivo(a). Quem era?',
    answerA: 'Severo Snape',
    answerB: 'Lucio Malfoy',
    answerC: 'Miverva McGonnagal',
    answerD: 'Rony Weasley',
  },
  {
    id: 10,
    name: 'questionJ',
    question: 'O sobrenome Potter era uma homenagem a alguém, quem era esse alguém?',
    answerA: 'Ashley Melina Potter, uma autora famosa de livros de terror e ficção que viveu entre 1665 e 1712',
    answerB: 'Helen Beatrix Potter, uma escritora famosa de livros infantis que viveu entre 1866 e 1943',
    answerC: 'Pietro Salssazar Potter, um general americano que viveu entre 1760 e 1799, eternizado pela criação de um dos orfanatos mais famosos dos EUA',
    answerD: 'Maria Potter Scallaver, uma médica canadense que cuidava de crianças com problemas especiais e viveu entre 1891 e 1943',
  },
];

export default QuestionsMedium;
