import { IPrimativeQuestion } from '../../../Interfaces/IQuestion';

const QuestionsEasy: IPrimativeQuestion[] = [
  {
    id: 1,
    name: 'questionA',
    question: 'Qual era a casa para qual o chapéu seletor queria enviar Harry Potter?',
    answerA: 'Grifinória',
    answerB: 'Sonserina',
    answerC: 'Lufa-Lufa',
    answerD: 'Corvinal',
  },
  {
    id: 2,
    name: 'questionB',
    question: 'Quantas casas existem em Hogwarts?',
    answerA: '4',
    answerB: '3',
    answerC: '2',
    answerD: '1',
  },
  {
    id: 3,
    name: 'questionC',
    question: 'Qual o patrono de Harry Potter?',
    answerA: 'Garça',
    answerB: 'Elefante',
    answerC: 'Cervo',
    answerD: 'Pomba',
  },
  {
    id: 4,
    name: 'questionD',
    question: 'Quem é Alvo Dumbledore?',
    answerA: 'Diretor de Hogwarts',
    answerB: 'Professor em Hogwarts',
    answerC: 'Pai de Harry Potter',
    answerD: 'Um comensal da morte',
  },
  {
    id: 5,
    name: 'questionE',
    question: 'Qual o nome da autora de Harry Potter?',
    answerA: 'Belatrix Lestrange',
    answerB: 'Minerva McGonal',
    answerC: 'Ravena Ravenclaw',
    answerD: 'J.K. Rowling',
  },
  {
    id: 6,
    name: 'questionF',
    question: 'Qual era o nome do rato de Rony Wesley?',
    answerA: 'Picucho',
    answerB: 'Rabixo',
    answerC: 'Perebas',
    answerD: 'Manicoto',
  },
  {
    id: 7,
    name: 'questionG',
    question: 'Quem é Voldemort?',
    answerA: 'O autor de Harry Potter',
    answerB: 'Diretor de Hogwarts',
    answerC: 'O maior bruxo das trevas',
    answerD: 'Ministro da magia',
  },
  {
    id: 8,
    name: 'questionH',
    question: 'O que Sirius Black era de Harry Potter?',
    answerA: 'Pai',
    answerB: 'Tio',
    answerC: 'Padrinho',
    answerD: 'Primo',
  },
  {
    id: 9,
    name: 'questionI',
    question: 'Qual era a cerveja tomada pelos jovens em Hogsmeade?',
    answerA: 'Apimentada',
    answerB: 'Amanteigada',
    answerC: 'Caramelizada',
    answerD: 'Pilsen',
  },
  {
    id: 10,
    name: 'questionJ',
    question: 'Para que servia a pedra filosofal no primeiro filme?',
    answerA: 'Ajudar Voldemort a restaurar seu poder',
    answerB: 'Matar Voldemort',
    answerC: 'Curar qualquer dor',
    answerD: 'Trazer riquezas sem medida a quem a portasse',
  },
];

export default QuestionsEasy;
