import { IPrimativeQuestion } from '../../../Interfaces/IQuestion';

const QuestionsMedium: IPrimativeQuestion[] = [
  {
    id: 1,
    name: 'questionA',
    question: 'Com quantos anos um aluno de Hogwarts recebe permissão para entrar em Hogsmeade?',
    answerA: 'Somente alunos do terceiro ano e os estudantes acima',
    answerB: 'Somente alunos do quinto ano',
    answerC: 'Somente alunos do segundo ano e os estudantes acima',
    answerD: 'Alunos do primero ano com a permissão dos pais',
  },
  {
    id: 2,
    name: 'questionB',
    question: 'Qual opção abaixo contém APENAS feitiços "proibidos" ou maldições imperdoáveis:',
    answerA: 'Crucio, Avada Kadabra, Tormento',
    answerB: 'Cruciatus, Imperius, Avada Kedavra',
    answerC: 'Imperius, Abada Kendavra, Cruciatus',
    answerD: 'Cruciatus, Alohomora, Avada Kedavra',
  },
  {
    id: 3,
    name: 'questionC',
    question: 'Qual o nome da mãe de Draco Malfoy',
    answerA: 'Belinda',
    answerB: 'Nairobi',
    answerC: 'Narcisa',
    answerD: 'Vanessa',
  },
  {
    id: 4,
    name: 'questionD',
    question: 'Quem é Peter Petigrew?',
    answerA: 'Diretor de Hogwarts',
    answerB: 'Professor em Hogwarts',
    answerC: 'Comensal da morte',
    answerD: 'Ministro da Justiça',
  },
  {
    id: 5,
    name: 'questionE',
    question: 'Qual o nome completo da autora de Harry Potter',
    answerA: 'Joanne K. Rowling',
    answerB: 'Jovenne K. Rowling',
    answerC: 'Julia K. Rowling',
    answerD: 'Jannet K. Rowling',
  },
  {
    id: 6,
    name: 'questionF',
    question: 'Qual o nome da vassoura que Harry Potter recebeu de presente da professora Minerva?',
    answerA: 'Nimbus 1000',
    answerB: 'Nimbus 3000',
    answerC: 'Nimbus 2000',
    answerD: 'Nimbus X',
  },
  {
    id: 7,
    name: 'questionG',
    question: 'Qual o nome completo da professora Minerva?',
    answerA: 'Minerva McGogall',
    answerB: 'Minervia MacGonagall',
    answerC: 'Minerva McGonagall',
    answerD: 'Minervus McGonagall',
  },
  {
    id: 8,
    name: 'questionH',
    question: 'Quem foi a pessoa usada por Voldemort no câmara secreta para declarar seu retorno a escola?',
    answerA: 'A gata do sr. Filtch',
    answerB: 'Nick quase sem cabeça',
    answerC: 'Hermione Granger',
    answerD: 'Gina Wesley',
  },
  {
    id: 9,
    name: 'questionI',
    question: 'Quantos filmes da saga Harry Potter existem?',
    answerA: '8',
    answerB: '6',
    answerC: '7',
    answerD: '5',
  },
  {
    id: 10,
    name: 'questionJ',
    question: 'Qual o nome real do ator que interpreta Harry Potter?',
    answerA: 'Daniel Rardliffe',
    answerB: 'Dominic Redliffe',
    answerC: 'David McLiffe',
    answerD: 'Daniel Radcliffe',
  },
];

export default QuestionsMedium;
